---
name: Deploy packages
on:
  workflow_dispatch:
  push:
    tags: [v*]
jobs:
  deploy-docker:
    uses: khanlab/actions/.github/workflows/workflow-release_task-deployDocker.yml@v0.2.1
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy-pypi:
    uses: khanlab/actions/.github/workflows/workflow-release_task-deployPypi.yml@v0.2.1
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
